### ISSUE TITLE
Component Request - BlockHours

### ISSUE THREAD

**Issue by pghorpade** [UCLALibrary/library-website-nuxt#299]
## Component Description

This component is used on Location Detail Page to display the location hours. 

## Design

Please also see attached screenshots for quick reference.

-   Desktop: https://www.figma.com/file/EKazRIMP4B15bD16UDbOwR/UCLA-Library-Design-System?node-id=1768%3A20731
     https://www.figma.com/file/EKazRIMP4B15bD16UDbOwR/UCLA-Library-Design-System?node-id=1768%3A21137
-   Tablet: https://www.figma.com/file/EKazRIMP4B15bD16UDbOwR/UCLA-Library-Design-System?node-id=1768%3A20732
-   Mobile: https://www.figma.com/file/EKazRIMP4B15bD16UDbOwR/UCLA-Library-Design-System?node-id=1768%3A20733
     https://www.figma.com/file/EKazRIMP4B15bD16UDbOwR/UCLA-Library-Design-System?node-id=1781%3A21595

## Slots

Name and description of any slots needed.

## Props

```js
props: {
    : {
     name: {
        type: String,
        default: ""
    },

    hours: {
        type: Array, // [{day, starttime, endtime, isClosed}]
            default: () => [],
    },
   
     internalLocations: {
          type: Array,
            default: () => [],
     }
   
}
```

## Developer Tips

List any developer tips here

1. For the current day highlight the column.
2. There is expand and collapse link which will hide or show the internal locations
3. [Accessible and responsive tips](https://inclusive-components.design/data-tables/) 
4. All Library Hours link goes to https://calendar.library.ucla.edu/hours

## Screenshots

<img width="310" alt="Screen Shot 2022-02-17 at 10 18 03 AM" src="https://user-images.githubusercontent.com/8161144/154543877-1e74a24a-2833-45dd-ad69-52fc4df793d3.png">
<img width="612" alt="Screen Shot 2022-02-17 at 10 17 44 AM" src="https://user-images.githubusercontent.com/8161144/154543878-e31f5b6f-cc2a-4606-ba05-5884c5d9aa9a.png">
<img width="590" alt="Screen Shot 2022-02-17 at 1 08 58 PM" src="https://user-images.githubusercontent.com/8161144/154543949-c29cd9d8-4004-4b21-8365-932c1cad6b0d.png">

**Comment by aprigge** [comment]
Closed with #349
